### ISSUE TITLE
Qt: Remember current symbol and instruction on File/Refresh

### ISSUE THREAD

**Issue by SimonKagstrom** [SimonKagstrom/emilpro#15]
I.e., if you are currently looking at main() and some instruction in the middle of it, this should again be centered if doing File/Refresh.

The same thing goes for the source view.

**Comment by m3gat0nn4ge** [comment]
Does it make sense to restore the current instruction on file refresh? Chances are the instruction and/or it's location would have changed no?

**Comment by SimonKagstrom** [comment]
In the general case, you're right, but in many cases it's doable to put the cursor on the current symbol + the offset you were at before Refresh and have pretty good results. The exact address will often not match, but the symbol is often there and the offset within the symbol is even in many cases correct if that particular piece of code didn't change.

**Comment by m3gat0nn4ge** [comment]
Cool .. I'll include the address

**Comment by SimonKagstrom** [comment]
Fixed by m3gat0nn4ge with c8b5f8b, thanks!
