### ISSUE TITLE
binutils backend simply does not recognize any object or executable files

### ISSUE THREAD

**Issue by RomanHargrave** [SimonKagstrom/emilpro#37]
It would appear (from the vague message "Error: not matching File format not recognized") that whatever emilpro is doing with binutils, is quite wrong.

Attempting to open any of the following ELF formats so far has resulted in this error:
- ELF 64-Bit v1 (/bin/ls, the emilpro binary)

I have not tested 32-Bit ELF, but if _that_ works, something is terribly wrong, seeing as there is not much significant difference between the two, if any, aside from instruction set extensions.

Not only that, but if emilpro is compiled without debugging symbols, it will crash.

**Comment by SimonKagstrom** [comment]
I'm afraid I can't reproduce this (x86_64). What system are you using, and did you build with any special options?
