### ISSUE TITLE
Missing disassembler?

### ISSUE THREAD

**Issue by RomanHargrave** [SimonKagstrom/emilpro#38]
When attempting to disassemble a section or object file, the following error is produced:

`Error: Disassembling attempted without disassembler`

This is strange, as it is implied that `emilpro` does not require any specific environment or path. That being said, I have binutils' objdump as well as a host of other disassemblers installed and find it strange that such an error occurs.

**Comment by SimonKagstrom** [comment]
It links against binutils and (optionally) capstone, so doesn't use the objdump binary or other disassemblers on the system.

It sounds like this is related to your other problem, but I can't reproduce this either I'm afraid (Fedora 22, x86_64).

**Comment by RomanHargrave** [comment]
@SimonKagstrom I should mention that I had to manually configure binutils, because the buildscript failed to do so.

**Comment by SimonKagstrom** [comment]
OK, interesting. How did configure fail in your build? And how did you configure your own build?

The build system checks out a particular commit of binutils, so at least that should be the same everywhere. The configure and build is done in cmake/BuildBinutils.cmake.

**Comment by RomanHargrave** [comment]
On Sat, 21 Nov 2015 11:49:02 -0800
Simon Kagstrom <notifications@github.com> wrote:

> OK, interesting. How did configure fail in your build? And how did you configure your own build?
> 
> The build system checks out a particular commit of binutils, so at least that should be the same everywhere. The configure and build is done in cmake/BuildBinutils.cmake.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/SimonKagstrom/emilpro/issues/38#issuecomment-158677266

When running the buildscript, it would successfully clone and check out binutils, after which it would fail to run binutis/configure, as it was cloning binutils in to binutils-gdb (or something like that).
I can get more details for you later.

-- 
Roman Hargrave <roman@hargrave.info>
http://hargrave.info
 _______________________________________
/ It is now pitch dark. If you proceed, \
\ you will likely fall into a pit.      /
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by SimonKagstrom** [comment]
Did you do a parallel build (make -j)? The build-binutils stuff isn't safe to build that way, due to my basic knowledge of cmake. Could you try building without -j?

**Comment by SimonKagstrom** [comment]
The new implementation uses capstone from conan so unlikely to be an issue anymore.
