### ISSUE TITLE
Segfault after loading another file and trying to view 'main' symbol.

### ISSUE THREAD

**Issue by cjwelborn** [SimonKagstrom/emilpro#50]
I've been having problems where I can load a file into EmilPro using the command line (`./emilpro myexecutable`), but the `File` -> `Open` method fails. Nothing gets loaded/refreshed. However, it gets worse if I load a file from the command line, and then try to load another file using `File` -> `Open`. The view is not refreshed, and if you try to view a symbol, by double-clicking on it, it causes a segfault.

System Info:
- Distro: Kubuntu (Xenial) 16.04.1 LTS
- Kernel: 4.4.0-57-generic x86_64

I'm new to assembly, and only know enough C to be dangerous, so forgive my ignorance. The executables I am trying to view were written and compiled by me on this same machine, with no fancy settings. By the way, I really like this application. It's simple enough to not overwhelm me, but has enough information that I can learn from. I especially like the instruction descriptions.

Steps to reproduce:

- Start emilpro by loading a file: `./emilpro myexecutable`
- Load another file from the menu: `File -> Open -> anotherexecutable`
- Double-click a symbol (I chose `main`).

Thanks for any insight you may have into this problem :smiley:.

**Comment by SimonKagstrom** [comment]
Thanks for the report! I will take a look at this, but it will probably not be until after new years eve.

**Comment by cjwelborn** [comment]
No problem, let me know if you need more info, or need me to try some things out. Have a great new year :tada:.

**Comment by SimonKagstrom** [comment]
I've tried this on the Qt port (which is what I'll focus on going forward, albeit slowly), and while it doesn't behave well, it doesn't crash.

Anyway, I'll keep the bug open and for now, the workaround by just opening a single file from the command line should be used :-)


By the way, the Qt port can be built with cmake for the src/qt/ directory, i.e.,

```
mkdir bld
cd bld
cmake ../src/qt
make
```

**Comment by cjwelborn** [comment]
Thanks I'll give it a shot.

**Comment by cjwelborn** [comment]
Got the Qt build going, I like it. I know you said it was rough, so I'm not complaining or anything. I just wanted to let you know about another segfault while I was messing with it.

`File -> Open` worked the first time I used it, any attempt to use it after that just seemed to refresh the view (with the first file I opened). Maybe it was just repainting it, and not really "refreshing" it. However, actually clicking on `Refresh` did cause a segfault. I got to see this output:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoull
Aborted (core dumped)
```

Anyway, just wanted to let you know about it. I'm still able to open files straight from the command line like you suggested so that's good. Again, EmilPRO is awesome. Thanks for making it. Let me know if you need any more info. :smile:

**Comment by SimonKagstrom** [comment]
Thanks for testing!

Yes, it's still not really finished, but I think it should be pretty much as good (or bad...) as the GTK port now. There are a few advantages with Qt which won't work in GTK, so in the long run it will be the only one.

**Comment by SimonKagstrom** [comment]
Restarted the entire implementation, so likely to have other issues, but not this particular error
