### ISSUE TITLE
use system binutils if it is available.

### ISSUE THREAD

**Issue by blshkv** [SimonKagstrom/emilpro#54]
It is common for a Linux distro to provide binutils including library by default. It can be also installed as dependency.

I suggest to look for the system library before installing it as bundled library.

https://github.com/pentoo/pentoo-overlay/blob/c1fc3c16b650188c8265c5b5f384f37f425b4011/dev-util/emilpro/files/emilpro-9999-system-binutils.patch

**Comment by SimonKagstrom** [comment]
Yes, I know, but I started building it because binutils-multiarch wasn't available as a development package, at least not in Ubuntu at the time. EmilPRO will only support the host architecture then. I'm not sure if this situation has changed since?

**Comment by blshkv** [comment]
sorry, no idea about other distros.  In gentoo, we can enable it via ```multitarget``` use flag.

ok then, do you think is it possible to add this additional check?

**Comment by SimonKagstrom** [comment]
I'm not quite sure how to check that binutils is actually a multiarch-variant unfortunately. Do you have any ideas?

I'll be offline (well, off-computer) for a while now FYI.

**Comment by SimonKagstrom** [comment]
The reimplementation I've started always uses the system binutils, so closing this.
