### ISSUE TITLE
the tool fails to compile with binutils-2.29.1

### ISSUE THREAD

**Issue by blshkv** [SimonKagstrom/emilpro#55]
this bug is continuation of https://github.com/SimonKagstrom/emilpro/issues/54

For more details, see the following report:
https://github.com/pentoo/pentoo-overlay/issues/254

**Comment by blshkv** [comment]
forgot to mentioned, there were dozen security bugs discovered in the previous versions (https://www.cvedetails.com/vulnerability-list/vendor_id-72/product_id-6825/GNU-Binutils.html)

so it is time to move on.

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/commit/54b62be155862d69f4b1b228833c73c8ffd7b8d2

**Comment by SimonKagstrom** [comment]
The reimplementation just uses  the system binutils, so closing.
