### ISSUE TITLE
Website is down: domain expired

### ISSUE THREAD

**Issue by ratijas** [SimonKagstrom/emilpro#59]
Time to host it on GitHub pages?

Archived view: https://web.archive.org/web/20160524074945/http://www.emilpro.com/

**Comment by SimonKagstrom** [comment]
Yes, I suppose it is.

Actually the web page itself is sort of meaningless and can just as well be handled by the README.md. However, it also used the site as a collaboration place where emilpro uploads instruction types, and that part can't be quite as easily replaced. Anyway, I doubt the network integration is very interesting to most people now anyway, so it can probably be done with.

**Comment by ratijas** [comment]
Are you implying that the project is dead for good?

**Comment by SimonKagstrom** [comment]
Sorry, no! As you might have seen, I'm not updating it myself anymore, but it's open source and anyone can chip in. I used to do lots of disassembly in my day-to-day work some years ago, but I no longer work at quite that low level, so my use of emilpro has dwindled.

However, I used to maintain the server part of it, and pay for the domain name etc, and I grew tired of that part of it. So it's expired and the server is down. The collaborative instruction description was, I think, a cool if very over designed idea, and for the actual benefit it gives it's in my opinion not worth it. Easier would have been to just put it in configuration files and handle updates through github pull requests.

**Comment by ratijas** [comment]
I see.  Makes sense to me.

In that case, if I may, I would suggest reflecting those recent changes in README. Specifically: remove dead link and add a note that the project is looking for active maintainers.

With that being said, I'm definitely not up to the task of maintaining EmilPro  — I never used it, and I'm not working with assembly much either. Well, It's interesting project anyway, and thanks for your time and effort!

**Comment by SimonKagstrom** [comment]
Yes, I'll refactor the README.md, thanks for bringing it up!

**Comment by ratijas** [comment]
... at the very least, I might end up building AUR package for Arch Linux. If I ever do that, I would send PR to the README here.

**Comment by SimonKagstrom** [comment]
I've restarted the project, and it won't have a web page outside of github anymore, so closing this issue.

That said, the emilpro.com domain now can be bought for $1095, so maybe I should have kept it :-)
